In [1]:
import numpy as np
import sys
from scipy import linalg, matmul

a. Define a matrix A <br> b. Define a vector b

In [2]:
A = np.arange(1,10).reshape(3,3)
b = [1,2,3]
print(A,b)

[[1 2 3]
 [4 5 6]
 [7 8 9]] [1, 2, 3]


c. Solve the linear system of equations A x = b

In [3]:
x = linalg.solve(A,b)
print(x)

[-0.23333333  0.46666667  0.1       ]


<ipython-input-3-8c2afac160e7>:1: LinAlgWarning: Ill-conditioned matrix (rcond=2.20282e-18): result may not be accurate.
  x = linalg.solve(A,b)


d. Check that your solution is correct by plugging it into the equation

In [4]:
check = np.matmul(A,x)
print(check)

[1. 2. 3.]


e. Repeat steps a-d using a random 3x3 matrix B (instead of the vector b)

In [5]:
A = np.arange(1,10).reshape(3,3)
B = np.random.rand(3,3)
print(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0.81758571 0.73756985 0.32169363]
 [0.46868413 0.87055114 0.70760821]
 [0.07936758 0.24754523 0.1954129 ]]


f. Solve the eigenvalue problem for the matrix A and print the eigenvalues and eigenvectors

In [6]:
eig_val, eig_vec = linalg.eig(A)
print(eig_val)
print(eig_vec)

[ 1.61168440e+01+0.j -1.11684397e+00+0.j -9.75918483e-16+0.j]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


g. Calculate the inverse, determinant of A

In [7]:
C=linalg.inv(A)
inv_D=linalg.det(C)
print(inv_D)
inv_D2 =linalg.det(linalg.inv(A))
print(inv_D2)

0.024499999999999914
0.024499999999999914


h. Calculate the norm of A with different orders

In [8]:
from scipy.linalg import norm

In [9]:
N1 = norm(A, None)
print(N1)

N2 = norm(A, np.inf)
print(N2)

N3 = norm(A, -np.inf)
print(N3)

16.881943016134134
24.0
6.0
